Repository readmeio/markdown, pull requests merged in 2020-12, with the labels that each got.

#86 chore: updating our style and testing deps
  jest.config.js
  package-lock.json
  package.json
Labels: scope:dependency

#87 chore: remove unused deps
  package-lock.json
  package.json
Labels: scope:dependency

#88 ci: setting up bundlewatch
  .github/workflows/bundlewatch.yml
  package.json
Labels: type:enhancement

#90 feat: treat react and react-dom as external deps
  package-lock.json
  package.json
  webpack.config.js
Labels: type:enhancement

#91 feat(release): add a next channel
  .github/workflows/release.yml
  .releaserc
Labels: type:enhancement

#97 chore(deps): update various dev dependencies
  package-lock.json
  package.json
Labels: scope:dependency

#98 chore(deps): bump @readme packages
  package-lock.json
  package.json
Labels: scope:dependency

#100 fix: user script extraction and execution
  __tests__/__snapshots__/magic-block-parser.test.js.snap
  __tests__/components/HTMLBlock.test.jsx
  __tests__/components/__snapshots__/test.js.snap
  __tests__/components/test.js
  components/HTMLBlock.jsx
  index.js
  processor/parse/magic-block-parser.js
  sanitize.schema.js
Labels: security, type:bug

#101 fix(bundlewatch): honor skip commit message
  .github/workflows/bundlewatch.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: type:workflow

#102 chore: don't run eslint on `test.watch`
  package.json
Labels: type:workflow

#103 test(HTMLBlock): move globals setup into `beforeEach` block
  __tests__/components/HTMLBlock.test.jsx
Labels: type:bug, type:workflow

#94 feat: visual regression testing and dev server app
  .github/workflows/ci.yml
  .gitignore
  Makefile
  Procfile
  __tests__/browser/ci/__diff_output__/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-callouts-without-surprises-1-diff.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-callouts-without-surprises-1-snap.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-code-block-tests-without-surprises-1-snap.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-code-block-vars-test-without-surprises-1-snap.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-code-blocks-without-surprises-1-snap.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-embeds-without-surprises-1-snap.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-features-without-surprises-1-snap.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-headings-without-surprises-1-snap.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-images-without-surprises-1-snap.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-lists-without-surprises-1-snap.png
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-tables-without-surprises-1-snap.png
  __tests__/browser/global-setup.js
  __tests__/browser/markdown.test.js
  __tests__/browser/setup.js
  example/Demo.jsx
  example/Fixtures/Syntax/callouts.md
  example/Fixtures/Syntax/code-blocks.md
  example/Fixtures/Syntax/code-blocks/code-block-tests.md
  example/Fixtures/Syntax/code-blocks/vars-test.md
  example/Fixtures/Syntax/embeds.md
  example/Fixtures/Syntax/features.md
  example/Fixtures/Syntax/headings.md
  example/Fixtures/Syntax/images.md
  example/Fixtures/Syntax/index.js
  example/Fixtures/Syntax/lists.md
  example/Fixtures/Syntax/tables.md
  example/Fixtures/index.jsx
  example/Header/index.jsx
  example/Router/index.jsx
  example/demo.scss
  example/favicon.ico
  example/img/nyt-thumbnail.jpg
  example/img/pizzabro.jpg
  example/img/readme-logo-white-on-blue.png
  example/index.html
  example/index.jsx
  jest-puppeteer.config.js
  jest.browser.js
  jest.common.js
  jest.config.js
  package-lock.json
  package.json
  webpack.common.js
  webpack.config.js
  webpack.dev.js
Labels: exploration, type:workflow

#105 docs: sync exported markdown to RDMD site
  .github/workflows/release.yml
  docs/callouts.md
  docs/code-block-tests.md
  docs/code-blocks.md
  docs/custom-css.md
  docs/embeds.md
  docs/features.md
  docs/getting-started.md
  docs/headings.md
  docs/images.md
  docs/lists.md
  docs/syntax-extensions.md
  docs/tables.md
  docs/variable-tests.md
  example/Fixtures/Syntax/embeds.md
  example/Fixtures/Syntax/images.md
  example/Fixtures/docs.js
  example/Fixtures/index.jsx
  example/Header/index.jsx
  example/demo.scss
  index.js
  package-lock.json
  package.json
Labels: scope:docs, type:enhancement

#107 docs: update docs to latest markdown
  docs/callouts.md
  docs/custom-css.md
  docs/embeds.md
  docs/getting-started.md
  docs/images.md
  docs/lists.md
  docs/tables.md
Labels: scope:docs
