Repository readmeio/markdown, pull requests merged in 2021-06, with the labels that each got.

#99 style(tables): hide empty table header rows
  components/Table/style.scss
Labels: type:styling

#185 chore(deps): upgrading syntax-highlighter to 10.8.0
  package-lock.json
  package.json
Labels: scope:dependency, type:enhancement

#203 fix: typos in variable subpackage exports
  __tests__/index.test.js
  index.js
  variable/index.jsx
Labels: type:bug
