Repository readmeio/markdown, pull requests merged in 2021-09, with the labels that each got.

#283 docs(readme): add Local Development section
  README.md
Labels: documentation

#303 fix(chore): bumping dependencies and resolving `npm audit` warnings
  .eslintignore
  .github/workflows/ci.yml
  package-lock.json
  package.json
  webpack.dev.js
Labels: dependencies

#308 chore(deps): bumping @readme/syntax-highlighter and @readme/variable
  package-lock.json
  package.json
Labels: dependencies

#309 chore(deps): bumping syntax-highlighter to support graphql
  package-lock.json
  package.json
Labels: enhancement, dependencies

#316 chore: package updates
  package-lock.json
  package.json
Labels: dependencies
