Repository readmeio/markdown, pull requests merged in 2021-12, with the labels that each got.

#390 fix: allow undefined code children
  __tests__/components/Code.test.jsx
  components/Code/index.jsx
  package-lock.json
  package.json
Labels: bug

#391 feat: upgrading syntax-highlighter to support Lua and Solidity
  README.md
  __tests__/browser/ci/markdown-test-js-visual-regression-tests-rdmd-syntax-renders-code-blocks-without-surprises-1-snap.png
  docs/code-blocks.md
  package-lock.json
  package.json
Labels: enhancement, dependencies

#394 fix: bumping @readme/syntax-highlighter to resolve upstram webpack issues
  package-lock.json
  package.json
Labels: bug, dependencies

#396 fix: upgrading syntax-highlighter to the latest release
  package-lock.json
  package.json
Labels: bug, dependencies

#399 feat: compile custom magic blocks
  __tests__/__snapshots__/flavored-compilers.test.js.snap
  __tests__/__snapshots__/magic-block-parser.test.js.snap
  __tests__/flavored-compilers.test.js
  __tests__/magic-block-parser.test.js
  package.json
  processor/compile/div.js
Labels: enhancement
