Repository readmeio/markdown, pull requests merged in 2021-02, with the labels that each got.

#127 docs: update the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type:workflow

#123 chore(deps): syntax-highlighter@10.4.4 + variable@11
  package-lock.json
  package.json
Labels: scope:dependency, type:bug

#129 docs: add disable tokenizers
  docs/getting-started.md
Labels: scope:docs

#119 feat: allow disabling tokenizers
  __tests__/__snapshots__/disabling-tokenizers.test.js.snap
  __tests__/__snapshots__/link-parsers.test.js.snap
  __tests__/disabling-tokenizers.test.js
  __tests__/flavored-compilers.test.js
  __tests__/flavored-parsers.test.js
  __tests__/index.test.js
  __tests__/link-parsers.test.js
  __tests__/magic-block-parser.test.js
  __tests__/magic-block-parser/table.test.js
  docs/getting-started.md
  index.js
  options.js
  options.json
  package-lock.json
  package.json
Labels: type:enhancement

#108 style: fix glossary term overflow in tables
  components/Table/style.scss
Labels: type:bug, type:styling
