Repository readmeio/markdown, pull requests merged in 2022-06, with the labels that each got.

#517 feat: add safeMode flag
  README.md
  __tests__/__snapshots__/magic-block-parser.test.js.snap
  __tests__/components/HTMLBlock.test.jsx
  __tests__/index.test.js
  components/HTMLBlock/index.jsx
  components/HTMLBlock/style.scss
  components/index.js
  example/Demo.jsx
  example/Fixtures/docs.js
  example/Fixtures/index.jsx
  example/demo.scss
  index.js
  options.js
  processor/parse/magic-block-parser.js
  styles/components.scss
Labels: enhancement, security

#519 fix: escape html when rendering in safeMode
  __tests__/components/HTMLBlock.test.jsx
  components/HTMLBlock/index.jsx
Labels: bug, security

#520 escapes support node
  __tests__/components/HTMLBlock.test.jsx
  components/HTMLBlock/index.jsx
  package-lock.json
  package.json
Labels: bug, security

#523 style(demo): polish sticky scrolling
  docs/getting-started.md
  example/Fixtures/index.jsx
  example/demo.scss
Labels: styles
